version: '3.9'
services:
  php-fpm:
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini

  nginx:
    build:
      context: ./docker
      dockerfile: ./nginx/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php-fpm
      - mysql-db

  mysql-db:
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    command: --init-file /var/www/html/sql/init.sql
    volumes:
      - ./docker/sql:/var/www/html/sql
